;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s --generate-func-effects --discard-func-effects --simplify-locals -S -o - | filecheck %s
;; This generates func effects, then discards them, then optimizes. That lets
;; us show that discarding does what it should.

(module
  ;; CHECK:      (global $glob (mut i32) (i32.const 0))
  (global $glob (mut i32) (i32.const 0))

  ;; CHECK:      (func $nop
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $nop
    ;; This function does nothing.
  )

  ;; CHECK:      (func $call-no-glob (result i32)
  ;; CHECK-NEXT:  (local $x i32)
  ;; CHECK-NEXT:  (local.set $x
  ;; CHECK-NEXT:   (global.get $glob)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $nop)
  ;; CHECK-NEXT:  (local.get $x)
  ;; CHECK-NEXT: )
  (func $call-no-glob (result i32)
    (local $x i32)
    (local.set $x
      (global.get $glob)
    )
    (call $nop) ;; this is ok to optimize over, if we had func effects, but
                ;; we discard them
    (local.get $x)
  )
)
