;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s --generate-func-effects --vacuum -S -o - | filecheck %s

(module
  ;; CHECK:      (func $calls
  ;; CHECK-NEXT:  (call $do-stuff)
  ;; CHECK-NEXT: )
  (func $calls
    ;; This function has no effects, so we can vacuum it out.
    (call $nop)
    ;; Likewise, this call also has no effects even though it returns a value
    ;; and takes a parameter.
    (drop
      (call $pure-i32
        (i32.const 42)
      )
    )
    ;; This function, however, has side effects and will remain.
    (call $do-stuff)
  )

  ;; CHECK:      (func $nop
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $nop
  )

  ;; CHECK:      (func $pure-i32 (param $x i32) (result i32)
  ;; CHECK-NEXT:  (i32.const 1337)
  ;; CHECK-NEXT: )
  (func $pure-i32 (param $x i32) (result i32)
    (i32.const 1337)
  )

  ;; CHECK:      (func $do-stuff
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT: )
  (func $do-stuff
    ;; This has side effects.
    (unreachable)
  )
)
